'use strict';

const fs = require('fs');
const path = require('path');
const resolver = require('opensphere-build-resolver/utils');

/**
 * Directory containing build artifacts generated by `opensphere-build-resolver`.
 * @type {string}
 */
const buildDir = '.build';

/**
 * Path to the build directory.
 * @type {string}
 */
const buildPath = path.join(__dirname, buildDir);

/**
 * Relative path of the built distribution directory.
 * @type {string}
 */
const appVersion = fs.readFileSync(path.join(buildPath, 'version'), 'utf8').trim().replace(/.*\//, '');

/**
 * Version value from the package.json file.
 * @type {string}
 */
const packageVersion = require('./package').version;

/**
 * Resources for `opensphere-build-index` to include in the distribution and `index.html`.
 * @type {Array<Object>}
 */
const indexResources = [
  {
    source: buildPath,
    target: '',
    scripts: ['modernizr.js']
  },
  {
    source: resolver.resolveModulePath('openlayers/dist', __dirname),
    target: 'vendor/openlayers',
    css: ['ol.css']
  },
  {
    source: resolver.resolveModulePath('bootstrap/dist', __dirname),
    target: 'vendor/bootstrap',
    css: ['css/bootstrap.min.css']
  },
  {
    source: resolver.resolveModulePath('jquery/dist', __dirname),
    target: 'vendor/jquery',
    scripts: ['jquery.min.js']
  },
  {
    source: resolver.resolveModulePath('moment/min', __dirname),
    target: 'vendor/moment',
    scripts: ['moment.min.js']
  },
  {
    source: resolver.resolveModulePath('angular', __dirname),
    target: 'vendor/angular',
    scripts: ['angular.min.js']
  },
  {
    source: resolver.resolveModulePath('angular-animate', __dirname),
    target: 'vendor/angular',
    scripts: ['angular-animate.min.js']
  },
  {
    source: resolver.resolveModulePath('angular-sanitize', __dirname),
    target: 'vendor/angular',
    scripts: ['angular-sanitize.min.js']
  },
  {
    source: resolver.resolveModulePath('angular-route', __dirname),
    target: 'vendor/angular',
    scripts: ['angular-route.min.js']
  },
  {
    source: resolver.resolveModulePath('opensphere/vendor/angular-ui', __dirname),
    target: 'vendor/angular',
    scripts: [
      'angular-ui.js',
      'angular-ui-utils/scroll/ui-scroll.js',
      'angular-ui-utils/scroll/ui-scroll-jqlite.js'
    ]
  },
  {
    source: resolver.resolveModulePath('cesium/Build/Cesium', __dirname),
    target: 'vendor/cesium',
    scripts: ['Cesium.js'],
    files: [
      'Assets',
      'ThirdParty',
      'Workers'
    ]
  },
  {
    source: resolver.resolveModulePath('opensphere-asm/dist', __dirname),
    target: '',
    scripts: ['os-load.js'],
    files: [
      'os-wasm.js',
      'os-wasm.wasm',
      'os-asm.js',
      'os-asm.js.mem'
    ]
  }
];

/**
 *
 */
module.exports = {
  appVersion: appVersion,
  packageVersion: packageVersion,
  basePath: __dirname,
  distPath: path.join('dist', 'opensphere-app-example'),
  templates: [
    {
      id: 'index',
      file: 'index-template.html',
      resources: indexResources
    }
  ],
  debugCss: path.join(buildDir, 'combined.css'),
  compiledCss: path.join(appVersion, 'styles', 'opensphere-app-example.min.css'),
  compiledJs: path.join(appVersion, 'opensphere-app-example.min.js')
};
